### ISSUE TITLE
Cannot import six from signac >= 1.3.0

### ISSUE THREAD

**Issue by bdice** [glotzerlab/signac-flow#211]
### Description

signac-flow versions <= 0.7.1 will not work with signac >= 1.3.0. In signac, support for Python 2.7 was dropped, which also meant we removed the vendored `six` package.

PR #157 to signac-flow removes the dependence on signac's vendored copy of six.py because signac-flow has also dropped support for Python 2.7. This will be fixed automatically by the release of signac-flow 0.9.0, but users of signac >= 1.3.0 will have to upgrade signac-flow to get the fix.

Two options for users to fix this temporarily:
1. Downgrade to signac 1.2.0.
2. Copy `six.py` into `site-packages/signac/common`.

_Reported on the signac Gitter channel: https://gitter.im/signac/Lobby?at=5e05c0372d574c7d1ec600b5_

### Error output

The error looks like:

```python
ImportError: cannot import name 'six' from 'signac.common' (/.../site-packages/signac/common/__init__.py)
```

### System configuration

Please complete the following information:

 - Version of signac: >= 1.3.0
 - Version of signac-flow: <= 0.7.1

**Comment by bdice** [comment]
signac-flow 0.9.0 has been released, which solves this. I will notify the Gitter channel and Slack channels that users may need to update signac-flow if they've recently updated signac.
