### PR TITLE
Fix status check when no operations are eligible

### LINKED ISSUE #607: Status check fails for Project with met postconditions
### Description

Minimal project with all postconditions met fails in signac-flow 0.18.0.

### To reproduce

Project file:
```python
# project.py
from flow import FlowProject


class Project(FlowProject):
    pass


@Project.operation
@Project.post(lambda job: True)
def op(job):
    pass


if __name__ == "__main__":
    Project().main()
```

### Error output
With `--show-traceback`:
```bash
$ python project.py status
Using environment configuration: StandardEnvironment

Fetching status:   0%|          | 0/1006 [00:00<?, ?it/s]
Fetching status: 100%|██████████| 1006/1006 [00:00<00:00, 458538.34it/s]

Fetching labels:   0%|          | 0/1006 [00:00<?, ?it/s]
Fetching labels: 100%|██████████| 1006/1006 [00:00<00:00, 851901.84it/s]
ERROR:flow.project:Error during status update: 'display_name'
Use '--ignore-errors' to complete the update anyways.
Traceback (most recent call last):
  File "/home/bdice/code/signac-flow/flow/project.py", line 4679, in _main_status
    self.print_status(jobs=aggregates, **args)
  File "/home/bdice/code/signac-flow/flow/project.py", line 3136, in print_status
    display_name = group_status["display_name"]
KeyError: 'display_name'
```

Without `--show-traceback`, I see another issue in how we're handling tracebacks when the traceback originates in signac-flow rather than in user code:
```bash
ERROR:flow.project:Error during status update: 'display_name'
Use '--ignore-errors' to complete the update anyways or '--show-traceback' to show the full traceback.
ERROR: Encountered error during program execution: ''NoneType' object has no attribute '__traceback__''
```

### System configuration

Please complete the following information:

 - Operating System [e.g. macOS]: Ubuntu 20.04
 - Version of Python [e.g. 3.7]: 3.8.10
 - Version of signac [e.g. 1.0]: 1.7.0
 - Version of signac-flow: 0.18.0

### PR DESCRIPTION
**Pull request by bdice**
## Description
This PR fixes a bug #607 introduced by #593. The key `"display_name"` does not exist for "placeholder operations," which are created to print an empty status line for jobs with no eligible operations.

**Once this PR and #608 are merged, we should create a patch release v0.18.1.**

## Motivation and Context
Resolves #607.

## Types of Changes
- [x] Bug fix

## Checklist:
- [x] I am familiar with the [**Contributing Guidelines**](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md).
- [x] I agree with the terms of the [**Contributor Agreement**](https://github.com/glotzerlab/signac-flow/blob/master/ContributorAgreement.md).
- [x] My name is on the [list of contributors](https://github.com/glotzerlab/signac-flow/blob/master/contributors.yaml).
- [x] My code follows the [code style guideline](https://github.com/glotzerlab/signac-flow/blob/master/CONTRIBUTING.md#code-style) of this project.
- [x] The changes introduced by this pull request are covered by existing or newly introduced tests.

If necessary:
- [ ] I have updated the API documentation as part of the package doc-strings.
- [ ] I have created a separate pull request to update the [framework documentation](https://docs.signac.io/) on [signac-docs](https://github.com/glotzerlab/signac-docs) and linked it here.
- [x] I have updated the [changelog](https://github.com/glotzerlab/signac-flow/blob/master/changelog.txt).

### CODE REVIEW

File: tests/test_project.py [hunk 1]
```diff
@@ -250,6 +250,30 @@ def test_status_performance(self):
...
+    @Project.operation
+    @Project.post(lambda job: True)
+    def foo(job):
+        pass
+
+    project_class = Project
+
+    def mock_project(self):
+        project = self.project_class.get_project(root=self._tmp_dir.name)
+        project.open_job(dict(i=0)).init()
```
Comment (vyasr) [inline tests/test_project.py:266]: Shouldn't pyupgrade fix this?
```suggestion
        project.open_job({i: 0}).init()
```

File: tests/test_project.py [hunk 2]
```diff
@@ -250,6 +250,30 @@ def test_status_performance(self):
...
+        return project
+
+    def test_status_no_eligible_operations(self):
+        """Test printing the project status when no operations are eligible."""
+        project = self.mock_project()
+        with redirect_stdout(StringIO()):
+            with redirect_stderr(StringIO()):
+                project.print_status()
```
Comment (vyasr) [inline tests/test_project.py:274]:
```suggestion
        with redirect_stdout(StringIO()),  redirect_stderr(StringIO()):
            project.print_status()
```

**Review by vyasr — APPROVED** [review]
A couple small suggestions, but nothing worth blocking over so address as you see fit. Thanks for fixing.

File: tests/test_project.py (hunk 2 above)
Comment (bdice) [reply tests/test_project.py:274]: I considered this but aimed for consistency with the existing test code instead. I'm going to leave this alone, if that's alright.

Comment (bdice) [reply tests/test_project.py:274]: I think a reasonable future change would be to add a context manager like `with silence_stdout_and_stderr()` that does both.

File: tests/test_project.py (hunk 1 above)
Comment (bdice) [reply tests/test_project.py]: I think `dict(**kwargs)` is left alone. I believe pyupgrade changes the empty call `dict()` to a literal `{}` and it will rewrite dictionary comprehensions: https://github.com/asottile/pyupgrade#dictionary-comprehensions

File: tests/test_project.py [hunk 3]
```diff
@@ -250,6 +250,30 @@ def test_status_performance(self):
...
+    @Project.operation
+    @Project.post(lambda job: True)
+    def foo(job):
+        pass
+
+    project_class = Project
+
+    def mock_project(self):
+        project = self.project_class.get_project(root=self._tmp_dir.name)
+        project.open_job({i: 0}).init()
```
Comment (bdice) [inline tests/test_project.py:266]:
```suggestion
        project.open_job({"i": 0}).init()
```

Comment (vyasr) [reply tests/test_project.py]: Whoops sorry my bad here.

File: tests/test_project.py (hunk 2 above)
Comment (vyasr) [reply tests/test_project.py:274]: Yeah that's fine. No reason to bother with two separate StringIO objects in that function either since we're just discarding the output anyway.

File: tests/test_project.py (hunk 1 above)
Comment (vyasr) [reply tests/test_project.py]: Ah I see.

**Review by b-butler — APPROVED** [review]
Thanks @bdice for fixing my bug.

**Review by tommy-waltmann — APPROVED** [review]
